### ISSUE TITLE
Possible Accuracy Difference between PyG and PyTorch implementation on Cora

### ISSUE THREAD

**Issue by mingloo** [chennnM/GCNII#1]
Hi @chennnM 

Thanks for sharing the GCNII code.

I've found there is some accuracy gap between PyG implementation and pure PyTorch implementation on Cora dataset.
See below table for details.

| Cora    | Layers | Metric |
|---------|--------|--------|
| PyTorch | 64     | 88.49  |
| PyG     | 64     | 85.00  |

Is there any possible parameter setting/code difference might cause the accuracy gap?

**Comment by chennnM** [comment]
> Hi @chennnM
> 
> Thanks for sharing the GCNII code.
> 
> I've found there is some accuracy gap between PyG implementation and pure PyTorch implementation on Cora dataset.
> See below table for details.
> 
> Cora	Layers	Metric
> PyTorch	64	88.49
> PyG	64	85.00
> Is there any possible parameter setting/code difference might cause the accuracy gap?

Hi @mingloo ,I use semi-supervised setting in PyG implementation, while 88.49 corresponds to semi-supervised task.

**Comment by mingloo** [comment]
> Hi @mingloo ,I use semi-supervised setting in PyG implementation, while 88.49 corresponds to semi-supervised task.


@chennnM Thanks for your reply.

PyG implementation is for semi-supervised setting while PyTorch implementation is for full-supervised.

**Comment by chennnM** [comment]
> > Hi @mingloo ,I use semi-supervised setting in PyG implementation, while 88.49 corresponds to semi-supervised task.
> 
> @chennnM Thanks for your reply.
> 
> PyG implementation is for semi-supervised setting while PyTorch implementation is for full-supervised.

you're right :)
