### ISSUE TITLE
A question about this framwork

### ISSUE THREAD

**Issue by tanjia123456** [chennnM/GCNII#3]
hello, I noticed GCNII framwork is spectral  domain.  Could you pealse recommend some fram on space domain?

**Comment by chennnM** [comment]
[GAT](https://github.com/PetarV-/GAT) and [GraphSAGE ](https://github.com/williamleif/GraphSAGE)are popular spatial domain methods. Especially, both [DGL](https://arxiv.org/abs/1909.01315) and [PyG](https://arxiv.org/abs/1903.02428) use the unified spatial domain framework to define GNN and implement numerous GNN variants.

**Comment by tanjia123456** [comment]
Ok， thank you very much
