### ISSUE TITLE
Questions about 100 runs

### ISSUE THREAD

**Issue by tpy1990wy** [chennnM/GCNII#5]
Great work！We are reproducing the statistical results in Table 2 and want to know how to design the 100 runs mentioned in the article for GCN and GCNII.  Use random seeds and fixed hyperparameters in Table 6?  Or some other method to select 100 runs?

**Comment by chennnM** [comment]
Hi, I used the hyperparameters in Table 6, commented out the code for setting seed, and repeated the network initialization and training 100 times.

**Comment by tpy1990wy** [comment]
@chennnM Thank you for your reply.
